### ISSUE TITLE
Hosting on Nuget.org

### ISSUE THREAD

**Issue by AwkEng** [NTIA/itm#4]
Thanks for publishing this repo.  Do you have plans to host the Nuget package on Nuget.org?

**Comment by wkozmaNTIA** [comment]
You're welcome.  We are currently investigating publishing the NuGet package on nuget.org.  However, because we are a part of a Federal agency, there are steps we must review first regarding the terms of nuget.org before we can publish.  At this time, I can not estimate the outcome or timeline as its partially subject to various competing priorities.
